name: Check and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkpublish:
    name: Check and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          path: .\BitwardenPS
          recurse: true
          includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
          output: results.sarif

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
    
      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        id: Build-Module
        with:
          script: | 
            Install-Module ModuleBuilder -Force
            Build-Module

      - name: Publish PowerShell Module
        uses: pcgeek86/publish-powershell-module-action@v20
        with:
          modulePath: .\Output\BitwardenPS
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
