name: Check and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@2044ae068e37d0161fa2127de04c19633882f061
        with:
          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: .\Output\BitwardenPS
          recurse: true
          # Include your own basic security rules. Removing this option will run all the rules
          includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
          output: results.sarif

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
    
      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        id: Build-Module
        with:
          script: | 
            Install-Module ModuleBuilder
            Build-Module

      - name: Publish PowerShell Module
        uses: pcgeek86/publish-powershell-module-action@v20
        with:
          modulePath: .\Output\BitwardenPS
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
