- name: Publish PowerShell Module
  # You may pin to the exact commit or the version.
  # uses: pcgeek86/publish-powershell-module-action@2a7837ce0746ea58c40574d8d6cbc6c44238edb7
  uses: pcgeek86/publish-powershell-module-action@v19
  with:
    # The filesystem path to the module to import into the environment.
    modulePath: "Output/BitwardenPS"
    # The NuGet API Key for PowerShell Gallery, with permission to push this module.
    NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
