name: Publish PSGallery

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish:
    name: Publish PSGallery
    runs-on: ubuntu-latest
    steps:
      - name: Publish PowerShell Module
        uses: pcgeek86/publish-powershell-module-action@v20
        with:
          modulePath: ./Output/BitwardenPS
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
